# Generated by Django 3.1.2 on 2020-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0003_auto_20201129_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.ManyToManyField(to='tutorial_index.Category'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
