# Generated by Django 3.1.2 on 2020-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0004_auto_20201129_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
