# Generated by Django 3.1.2 on 2020-12-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0007_auto_20201219_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='comments',
            field=models.ManyToManyField(blank=True, to='tutorial_index.Comment'),
        ),
    ]
