# Generated by Django 3.1.2 on 2020-12-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0014_auto_20201223_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(related_name='replied_to', to='tutorial_index.Comment'),
        ),
    ]
