# Generated by Django 3.1.2 on 2020-12-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0015_auto_20201223_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
