# Generated by Django 3.1.2 on 2020-12-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0019_auto_20201224_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
