# Generated by Django 3.1.2 on 2020-12-27 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0020_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_tutorials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replied_to', to='tutorial_index.Comment'),
        ),
    ]
