# Generated by Django 3.1.2 on 2020-12-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_index', '0023_auto_20201229_1927'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tutorial',
            order_with_respect_to=None,
        ),
    ]
